### PR TITLE
Modify Jsoncpp find package

### PR DESCRIPTION
**Pull request by edoardolombardi**
Modify Jsoncpp find package in order to use the proper external package and not the one hard embedded in netlicensing project.

Usage of a jsoncpp type is also fixed for the purpose.

### CODE REVIEW

**Comment by katemay** [comment]
So with this modification, we need to update both mimic and rombox CI immediately upon the merge of this pull request otherwise they will break, right?

**Comment by edoardolombardi** [comment]
> So with this modification, we need to update both mimic and rombox CI immediately upon the merge of this pull request otherwise they will break, right?

Yes, you're right. We could add a tag to use or the old version or the new one and add a small modification to the CIs.

**Comment by katemay** [comment]
I have updated the impacted rombox branches and tags so that its CI will not break. Whenever you want to merge this, team rombox is good with it.

**Comment by edoardolombardi** [comment]
Thanks @katemay, I'm noticing some issues with mimic server. I'm not understanding if these modifications beark some references/iterators. I put as draft to avoid premature merging,

**Pull request closed without merging**
